# Generated by Django 5.1.5 on 2025-01-29 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/%Y/%m/'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='testapp_use_usernam_5d3377_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='testapp_use_email_2325cc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['qr_code_data'], name='testapp_use_qr_code_a3b04d_idx'),
        ),
    ]
