# Generated by Django 5.1.5 on 2025-01-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='default/default_profile.jpg', null=True, upload_to='student_images/%Y/%m/'),
        ),
    ]
