# Generated by Django 5.1.4 on 2025-02-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('testapp', '0009_user_fingerprint_data_user_fingerprint_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='fingerprint_data',
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_template',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_template_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['fingerprint_template_hash'], name='testapp_use_fingerp_34aab2_idx'),
        ),
    ]
