# Generated by Django 5.1.4 on 2025-02-03 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_user_options_remove_user_fingerprint_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'volunteer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
