# Generated by Django 5.1.4 on 2025-02-04 11:23

import testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_user_verified_at_user_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='default/default_profile.jpg', null=True, upload_to=testapp.models.user_image_upload_path),
        ),
    ]
