# Generated by Django 5.1.4 on 2025-02-04 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, unique=False),
            preserve_default=False,
        ),
    ]
